services:
  fuseki:
    build: ./fuseki  # build from fuseki directory using Dockerfile
    container_name: pm-fuseki
    ports:
      - "3030:3030"  # Maps the internal port 3030 in the container to the host machine's 3030
    volumes:
      - ./fuseki/config.ttl:/opt/fuseki/config.ttl  # Bind mount the config file
      - fuseki-data:/opt/fuseki/databases  # Named volume for databases
      - fuseki-config:/opt/fuseki/configuration  # Named volume for dataset configurations
      - ./fuseki/rules:/opt/fuseki/rules  # Bind mount the rules directory
      - ./fuseki/ontology:/opt/fuseki/ontology  # Bind mount the ontology directory
    environment:
      - FUSEKI_HOME=/opt/fuseki
      - FUSEKI_BASE=/opt/fuseki

volumes:
  fuseki-data:
    driver: local
  fuseki-config:
    driver: local
